import { Business } from "@/types";
import { EXTRA_BUSINESSES_1 } from './businesses-extra-1';
import { EXTRA_BUSINESSES_2 } from './businesses-extra-2';
import { EXTRA_BUSINESSES_3 } from './businesses-extra-3';
import { EXTRA_BUSINESSES_4 } from './businesses-extra-4';
import { EXTRA_BUSINESSES_5 } from './businesses-extra-5';

const BASE_BUSINESSES: Business[] = [

  // ─── RESTAURANTS ──────────────────────────────────────────────
  {
    id: '1',
    name: 'Mitra Samaj',
    category: 'restaurants',
    rating: 4.2,
    reviewCount: 3168,
    address: 'Sri Krishna Temple Complex, Thenkpete, Maruthi Veethika',
    area: 'Car Street',
    phone: '+91 98801 99678',
    tags: ['Vegetarian', 'South Indian', 'Breakfast', 'Masala Dosa'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&q=80',
    openTime: '6:10 AM',
    closeTime: '12:30 PM',
    description: 'Legendary South Indian breakfast restaurant near Sri Krishna Temple. Famous as the birthplace of Masala Dosa. Their Mangalore Buns, Pineapple Sheer and Gobi Bajje are legendary. Visited by thousands daily.'
  },
  {
    id: '2',
    name: 'Diana Restaurant',
    category: 'restaurants',
    rating: 4.5,
    reviewCount: 2841,
    address: 'Court Road, Old Town',
    area: 'Old Town',
    phone: '+91 82022 25454',
    tags: ['Gadbad Ice Cream', 'Snacks', 'Desserts', 'Sea Food'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '10:30 PM',
    description: 'Birthplace of the iconic Gadbad Ice Cream — a Udupi legend since the 1960s. The layered dessert made of mixed ice creams, jelly, nuts and fruits is a must-try for every visitor to Udupi.'
  },
  {
    id: '3',
    name: 'Woodlands Restaurant',
    category: 'restaurants',
    rating: 4.3,
    reviewCount: 1892,
    address: 'Main Road, Near KSRTC Bus Stand',
    area: 'City Center',
    phone: '+91 82022 20123',
    tags: ['South Indian', 'North Indian', 'Thali', 'Moode Idli'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '10:00 PM',
    description: 'One of Udupi\'s oldest restaurants — renowned for authentic Udupi Thali and the famous Moode Idli. A heritage institution loved by locals and tourists alike.'
  },
  {
    id: '4',
    name: 'Hotel Durga Prasad',
    category: 'restaurants',
    rating: 4.5,
    reviewCount: 342,
    address: 'Car Street, Near Krishna Mutt',
    area: 'Car Street',
    phone: '+91 82020 12345',
    tags: ['Vegetarian', 'South Indian', 'Breakfast', 'Thali'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '10:00 PM',
    description: 'One of the most famous Udupi restaurants serving authentic South Indian cuisine since 1952. Their Idli-Vada, Dosa and evening tiffin are consistently excellent.'
  },
  {
    id: '5',
    name: "Pabba's Ice Cream Parlour",
    category: 'restaurants',
    rating: 4.4,
    reviewCount: 1456,
    address: 'Car Street, Udupi',
    area: 'Car Street',
    phone: '+91 82022 23344',
    tags: ['Ice Cream', 'Desserts', 'Fruit Shakes', 'Sundae'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    description: 'Famous ice cream parlour in Udupi known for unique flavours including Gadbad, Tender Coconut, and locally inspired creations. A beloved institution since decades.'
  },
  {
    id: '6',
    name: 'MTR — Mavalli Tiffin Rooms',
    category: 'restaurants',
    rating: 4.4,
    reviewCount: 987,
    address: 'Manipal Main Road, Near Manipal University',
    area: 'Manipal',
    phone: '+91 82025 11222',
    tags: ['Karnataka Cuisine', 'Thali', 'Breakfast', 'Filter Coffee'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    openTime: '7:30 AM',
    closeTime: '9:00 PM',
    description: 'The iconic MTR brand brings its legendary Karnataka-style South Indian Thali to Manipal. Famous for fluffy Rava Idlis, crispy Dosas, and authentic filter coffee.'
  },
  {
    id: '7',
    name: 'Samanvay Boutique Hotel Restaurant',
    category: 'restaurants',
    rating: 4.2,
    reviewCount: 534,
    address: 'KM Marg, Udupi City',
    area: 'City Center',
    phone: '+91 82022 29900',
    tags: ['Buffet', 'Breakfast', 'South Indian', 'Sea Food'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '11:00 PM',
    description: 'Praised for their impressive breakfast buffet featuring authentic coastal Karnataka dishes. The hotel\'s restaurant is popular among tourists seeking local flavours in a comfortable setting.'
  },
  {
    id: '8',
    name: 'Malpe Harbour Sea Food Centre',
    category: 'restaurants',
    rating: 4.6,
    reviewCount: 1123,
    address: 'Malpe Harbour Road, Near Ferry Point',
    area: 'Malpe',
    phone: '+91 94480 55667',
    tags: ['Sea Food', 'Fish Curry', 'Prawn Fry', 'Coastal'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80',
    openTime: '11:00 AM',
    closeTime: '10:30 PM',
    description: 'Fresh-catch seafood straight from Malpe harbour. Famous for Fish Rava Fry, Crab Masala, and Surmai (King Fish) curries cooked in authentic coastal Karnataka style.'
  },
  {
    id: '9',
    name: 'Hotel Kediyoor',
    category: 'restaurants',
    rating: 4.1,
    reviewCount: 678,
    address: 'Kalsanka, Udupi',
    area: 'Kalsanka',
    phone: '+91 82022 22600',
    tags: ['Vegetarian', 'Jain Food', 'South Indian', 'North Indian'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '10:00 PM',
    description: 'A trusted name in Udupi\'s dining scene with consistent quality and value. Known for their pure vegetarian menu and courteous service.'
  },
  {
    id: '10',
    name: 'Coastal Kitchen — Spice Route',
    category: 'restaurants',
    rating: 4.3,
    reviewCount: 445,
    address: 'NH 66, Near Parkala Junction',
    area: 'Parkala',
    phone: '+91 96200 34567',
    tags: ['Coastal', 'Non-Veg', 'Chicken', 'Seafood', 'Mangalore Style'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&q=80',
    openTime: '11:00 AM',
    closeTime: '11:00 PM',
    description: 'Authentic coastal Karnataka cuisine with a spicy Mangalurean touch. Chicken Ghee Roast, Kori Rotti and Bangude Masala are their signature dishes.'
  },

  // ─── HOSPITALS / DOCTORS ──────────────────────────────────────
  {
    id: '11',
    name: 'Kasturba Hospital Manipal',
    category: 'doctors',
    rating: 4.7,
    reviewCount: 5892,
    address: 'Tiger Circle Road, Manipal',
    area: 'Manipal',
    phone: '+91 82022 22222',
    tags: ['Multi-Specialty', 'Tertiary Care', '24/7 Emergency', 'NABH Accredited'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Tier-3 tertiary care hospital under Manipal Academy of Higher Education. World-class facilities with 2000+ beds, cutting-edge medical technology, and specialists across all departments.'
  },
  {
    id: '12',
    name: 'Dr. TMA Pai Hospital',
    category: 'doctors',
    rating: 4.6,
    reviewCount: 2341,
    address: 'KM Marg, Near Corporation Bank Main Branch, Udupi',
    area: 'City Center',
    phone: '+91 82022 28100',
    tags: ['Multi-Specialty', '200 Beds', 'ICU', 'Surgery', 'Gynaecology'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Established 1984 under Manipal Academy. 200-bed secondary-plus facility with ICUs, 4 operation theatres, dialysis, endoscopy, and specialized departments including Orthopaedics, Ophthalmology & ENT.'
  },
  {
    id: '13',
    name: 'Gandhi Hospital',
    category: 'doctors',
    rating: 4.4,
    reviewCount: 1678,
    address: 'Bannanje, Near Krishna Temple, Udupi',
    area: 'Bannanje',
    phone: '+91 82022 21000',
    tags: ['75+ Beds', 'Maternity', 'General Surgery', 'Emergency'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Serving Udupi since 1995 with over 30 years of dedicated healthcare. Known for personal care and patient-centric approach. 75+ beds with modern equipment and experienced specialists.'
  },
  {
    id: '14',
    name: 'Dr. Suresh Shetty — General Physician',
    category: 'doctors',
    rating: 4.7,
    reviewCount: 156,
    address: 'KC Road, Near State Bank of India',
    area: 'KC Road',
    phone: '+91 82020 34567',
    tags: ['General Physician', 'Family Medicine', 'Diabetologist'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '6:00 PM',
    description: 'Experienced general physician with 20+ years of practice. Specialises in diabetes management, hypertension, and preventive care. Highly trusted by Udupi residents.'
  },
  {
    id: '15',
    name: 'City Eye Hospital',
    category: 'doctors',
    rating: 4.5,
    reviewCount: 892,
    address: 'KM Marg, Udupi',
    area: 'City Center',
    phone: '+91 82022 24400',
    tags: ['Ophthalmology', 'LASIK', 'Cataract Surgery', 'Eye Care'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '6:00 PM',
    description: 'Leading eye care centre offering comprehensive eye examinations, cataract surgery, LASIK procedures, and optical dispensing services in Udupi district.'
  },
  {
    id: '16',
    name: 'Shree Devi Dental Clinic',
    category: 'doctors',
    rating: 4.4,
    reviewCount: 312,
    address: 'Manipal Main Road, Near Manipal Flyover',
    area: 'Manipal',
    phone: '+91 82025 33445',
    tags: ['Dentist', 'Orthodontics', 'Implants', 'Root Canal'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1588776814546-1ffbb0ff0e39?w=400&q=80',
    openTime: '9:30 AM',
    closeTime: '7:00 PM',
    description: 'Modern dental clinic offering a full range of dental treatments — cosmetic dentistry, implants, braces, root canal therapy, and pain-free extractions.'
  },
  {
    id: '17',
    name: 'Udupi Ayurvedic Hospital',
    category: 'doctors',
    rating: 4.3,
    reviewCount: 445,
    address: 'Ajjarakadu, Near Old Bus Stand',
    area: 'Ajjarakadu',
    phone: '+91 82022 26677',
    tags: ['Ayurveda', 'Panchakarma', 'Herbal', 'Traditional Medicine'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '6:00 PM',
    description: 'Traditional Ayurvedic treatment centre specialising in Panchakarma therapy, herbal medicine, and holistic wellness treatments following authentic Kerala and Karnataka traditions.'
  },
  {
    id: '18',
    name: 'Apollo Pharmacy — Udupi',
    category: 'doctors',
    rating: 4.2,
    reviewCount: 234,
    address: 'Car Street, Near Temple',
    area: 'Car Street',
    phone: '+91 82022 20001',
    tags: ['Pharmacy', '24/7', 'Medicines', 'Health Products'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '11:00 PM',
    description: 'Well-stocked pharmacy near Udupi city centre with a wide range of prescription and OTC medicines, health supplements, and baby care products.'
  },

  // ─── HOTELS / RESORTS ─────────────────────────────────────────
  {
    id: '19',
    name: 'Scylla Luxury Resort & Spa',
    category: 'hotels',
    rating: 4.8,
    reviewCount: 1247,
    address: 'Yermal, Malpe Road, Udupi District',
    area: 'Yermal',
    phone: '+91 77600 99700',
    tags: ['Beachfront', 'Luxury', 'Spa', 'Sea View', 'Jacuzzi', 'Arabian Sea'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'A beachfront luxury sanctuary on the Arabian Sea coastline. 25 smart ocean-view suites including Jacuzzi suites, duplex suites, and sea-view rooms. Features LANA Spa, fine dining restaurant CETUS, and Poseidon Activity Centre.'
  },
  {
    id: '20',
    name: 'Hermes Resort & Spa',
    category: 'hotels',
    rating: 4.5,
    reviewCount: 2134,
    address: 'Kadike Beach Road, Near Malpe Beach, Udupi',
    area: 'Malpe',
    phone: '+91 82022 37700',
    tags: ['Swimming Pool', 'Waterpark', 'Beach', 'Family', 'Wedding Venue'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Best resort hotel in Udupi with a swimming pool and waterpark. Just 500m from Kadike Beach and 3km from Malpe Beach. Offers luxury rooms, indoor/outdoor restaurants AMBROSIA and OASIS, and wedding venues for 1000+ guests.'
  },
  {
    id: '21',
    name: 'Udupi Residency Hotel',
    category: 'hotels',
    rating: 4.2,
    reviewCount: 267,
    address: 'KM Marg, City Center',
    area: 'City Center',
    phone: '+91 82022 23300',
    tags: ['3 Star', 'AC Rooms', 'Wi-Fi', 'Restaurant', 'Parking'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Comfortable 3-star hotel in the heart of Udupi city. Well-appointed rooms with modern amenities, in-house restaurant, conference facilities, and easy access to the Krishna Temple.'
  },
  {
    id: '22',
    name: 'Hotel Central Park — Manipal',
    category: 'hotels',
    rating: 4.1,
    reviewCount: 789,
    address: 'Survey No 61/3, Udipi Main Road, Shivalli, Manipal',
    area: 'Manipal',
    phone: '+91 82025 57700',
    tags: ['Manipal', 'Business Hotel', 'AC', 'Wi-Fi', 'Restaurant'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Conveniently located in Manipal near the university. Popular with visiting families and business travellers. Houses Lakme Salon and an in-house restaurant.'
  },
  {
    id: '23',
    name: 'Paradise Isle Beach Resort',
    category: 'hotels',
    rating: 4.3,
    reviewCount: 563,
    address: 'Malpe Beach Road, St. Mary\'s Islands Jetty',
    area: 'Malpe',
    phone: '+91 94480 22234',
    tags: ['Beach Resort', 'Watersports', 'Boat Rides', 'Family'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Beachside resort offering an ideal gateway for water sports and tours to St. Mary\'s Islands. Comfortable rooms, local cuisine, and easy access to Malpe beach activities.'
  },
  {
    id: '24',
    name: 'Manipal Comforts Hotel',
    category: 'hotels',
    rating: 3.9,
    reviewCount: 412,
    address: 'Near Tiger Circle, Manipal',
    area: 'Manipal',
    phone: '+91 82025 44400',
    tags: ['Budget Hotel', 'Student Friendly', 'Hostel', 'AC'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Affordable and clean accommodation near Manipal University ideal for visiting parents and budget travellers. Close to all campus facilities and shopping.'
  },

  // ─── BEAUTY / SALONS ──────────────────────────────────────────
  {
    id: '25',
    name: 'Kimera Wellness Spa & Salon',
    category: 'beauty',
    rating: 4.8,
    reviewCount: 4382,
    address: '1st Floor, Shri Rastu Building, Behind Manipal University, Dr VS Acharya Rd',
    area: 'Manipal',
    phone: '+91 97401 73282',
    tags: ['Unisex', 'Hair', 'Spa', 'Skin', 'Nail Extensions', 'Luxury'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1560066984-138daaa0c9a4?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '8:00 PM',
    description: 'Udupi-Manipal\'s top-rated luxury spa and salon. Excellent hair styling, nail extensions, and relaxing therapies. Professional staff — highly recommended for haircuts, hair colour, and skin treatments.'
  },
  {
    id: '26',
    name: 'Lakme Salon — Manipal',
    category: 'beauty',
    rating: 4.5,
    reviewCount: 1234,
    address: 'Survey No 61/3, Hotel Central Park Building, Udipi Main Road, Shivalli',
    area: 'Manipal',
    phone: '+91 82025 77900',
    tags: ['Lakme', 'Bridal', 'Hair Colour', 'HydraFacial', 'Unisex'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '8:00 PM',
    description: 'Official Lakme Salon in Manipal offering exclusive Runway Secrets services. Expert hair colour, bridal makeup with the signature Ethereal Bloom collection, HydraFacial, and nail art.'
  },
  {
    id: '27',
    name: 'Glamour Zone Salon',
    category: 'beauty',
    rating: 4.3,
    reviewCount: 203,
    address: 'Manipal Centre, Near PVS Roundana',
    area: 'Manipal',
    phone: '+91 82020 89012',
    tags: ['Hair', 'Bridal', 'Spa', 'Mehendi', 'Unisex'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '8:00 PM',
    description: 'Premium unisex salon offering complete beauty and grooming services. Specialises in bridal packages, hair treatments, and full-body spa sessions.'
  },
  {
    id: '28',
    name: 'Glow Beauty Studio',
    category: 'beauty',
    rating: 4.2,
    reviewCount: 178,
    address: 'Bannanje Road, Udupi',
    area: 'Bannanje',
    phone: '+91 90360 44556',
    tags: ['Ladies Salon', 'Facial', 'Threading', 'Hair'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '7:30 PM',
    description: 'A popular ladies beauty studio in Udupi offering affordable facials, threading, hair treatments, and bridal makeup services in a friendly environment.'
  },
  {
    id: '29',
    name: 'The Barber Club — Men\'s Grooming',
    category: 'beauty',
    rating: 4.4,
    reviewCount: 345,
    address: 'Tiger Circle Road, Manipal',
    area: 'Manipal',
    phone: '+91 96860 22233',
    tags: ['Mens Salon', 'Haircut', 'Beard', 'Skin Care', 'Styling'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '9:00 PM',
    description: 'Udupi\'s premium men\'s grooming lounge. Expert cuts, beard shaping, hot towel shaves, and skin treatments. Appointment-based for shorter wait times.'
  },

  // ─── GYM / FITNESS ────────────────────────────────────────────
  {
    id: '30',
    name: 'Coastal Fitness Studio',
    category: 'gym',
    rating: 4.4,
    reviewCount: 89,
    address: 'Bypass Road, Near SBI ATM',
    area: 'Bypass Road',
    phone: '+91 82020 67890',
    tags: ['AC Gym', 'Personal Training', 'Yoga', 'CrossFit'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80',
    openTime: '5:30 AM',
    closeTime: '10:00 PM',
    description: 'Modern fitness studio with state-of-the-art cardio and strength equipment. Certified personal trainers, yoga classes, and Zumba sessions. AC hall, parking, and locker rooms.'
  },
  {
    id: '31',
    name: 'Cult.fit — Manipal',
    category: 'gym',
    rating: 4.5,
    reviewCount: 567,
    address: 'Near Manipal University Main Gate, Manipal',
    area: 'Manipal',
    phone: '+91 95354 22100',
    tags: ['HIIT', 'Yoga', 'Cycling', 'Boxing', 'Nutrition'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80',
    openTime: '5:00 AM',
    closeTime: '11:00 PM',
    description: 'Popular Cult.fit centre near Manipal University. Offers HIIT, yoga, strength, cycling, and boxing classes with certified instructors. Student discounts available.'
  },
  {
    id: '32',
    name: 'Iron Paradise Gym',
    category: 'gym',
    rating: 4.2,
    reviewCount: 212,
    address: 'Kinnimulki, Near Old Bus Stand',
    area: 'Kinnimulki',
    phone: '+91 94480 33344',
    tags: ['Bodybuilding', 'Weight Training', 'Supplements', 'Stepper'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&q=80',
    openTime: '5:30 AM',
    closeTime: '9:30 PM',
    description: 'Dedicated strength and bodybuilding gym with heavy-duty equipment, dumbbells up to 50kg, and experienced coaching. Supplement store on-site.'
  },
  {
    id: '33',
    name: 'Udupi Yoga & Wellness Centre',
    category: 'gym',
    rating: 4.6,
    reviewCount: 134,
    address: 'Shivalli Village, Near MAHE Campus',
    area: 'Shivalli',
    phone: '+91 96117 55678',
    tags: ['Yoga', 'Meditation', 'Ayurvedic Wellness', 'Pranayama'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80',
    openTime: '6:00 AM',
    closeTime: '8:00 PM',
    description: 'Holistic wellness centre offering traditional Hatha yoga, meditation, pranayama, and Ayurvedic wellness programmes in a serene environment near the MAHE campus.'
  },

  // ─── TRAVEL ───────────────────────────────────────────────────
  {
    id: '34',
    name: 'Shree Travels Udupi',
    category: 'travel',
    rating: 4.1,
    reviewCount: 134,
    address: 'Bus Stand Road, Near KSRTC',
    area: 'Bus Stand',
    phone: '+91 82022 25055',
    tags: ['Bus Booking', 'Tour Packages', 'Car Rental', 'Pilgrimages'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '8:00 PM',
    description: 'Complete travel solutions including religious pilgrimage tours, Goa, Coorg, and Ooty packages, bus ticket booking, and car rentals for corporate travel in coastal Karnataka.'
  },
  {
    id: '35',
    name: 'Malpe Boat Tours & Water Sports',
    category: 'travel',
    rating: 4.6,
    reviewCount: 2345,
    address: 'Malpe Harbour, Jetty Road, Malpe',
    area: 'Malpe',
    phone: '+91 94480 78800',
    tags: ['Boat Rides', "St Mary's Islands", 'Water Sports', 'Snorkelling', 'Fishing'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '5:00 PM',
    description: 'Official boat tours from Malpe Harbour to St. Mary\'s Islands — famous for stunning hexagonal basalt rock formations. Also offers water sports, snorkelling, banana boat rides, and sea fishing.'
  },
  {
    id: '36',
    name: 'Karnataka Tourism Information Centre',
    category: 'travel',
    rating: 4.0,
    reviewCount: 89,
    address: 'KSTDC Office, City Center, Udupi',
    area: 'City Center',
    phone: '+91 82022 22577',
    tags: ['Government', 'Tour Info', 'Packages', 'Maps', 'Guides'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '5:30 PM',
    description: 'Official Karnataka State Tourism Development Corporation office for Udupi. Get tourist information, government tour packages, accommodation bookings, and local guide services.'
  },
  {
    id: '37',
    name: 'Blue Bird Travels',
    category: 'travel',
    rating: 4.2,
    reviewCount: 312,
    address: 'Ajjarakadu, Near Canara Bank',
    area: 'Ajjarakadu',
    phone: '+91 82022 27788',
    tags: ['Air Tickets', 'Hotel Booking', 'Honeymoon Packages', 'Visa'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '7:00 PM',
    description: 'Full-service travel agency offering flight bookings, hotel reservations, honeymoon and vacation packages, visa assistance, and travel insurance for domestic and international travel.'
  },
  {
    id: '38',
    name: 'Udupi Cabs — 24/7 Taxi Service',
    category: 'travel',
    rating: 4.3,
    reviewCount: 876,
    address: 'City Center, Udupi',
    area: 'City Center',
    phone: '+91 98860 55555',
    tags: ['Cab', 'Taxi', 'Mangalore Airport', 'Outstation', '24/7'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: '24/7 reliable cab service in Udupi. Airport transfers to Mangaluru Airport (57 km), outstation trips to Goa, Bangalore, Mysore, and local sightseeing. AC and non-AC vehicles available.'
  },

  // ─── EDUCATION ────────────────────────────────────────────────
  {
    id: '39',
    name: 'Manipal Academy of Higher Education (MAHE)',
    category: 'education',
    rating: 4.7,
    reviewCount: 12456,
    address: 'Madhav Nagar, Manipal',
    area: 'Manipal',
    phone: '+91 82022 22292',
    tags: ['University', 'Deemed University', 'Medicine', 'Engineering', 'Management'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '6:00 PM',
    description: 'India\'s top-ranked private deemed university. Home to 28,000+ students from 57 countries. Offers programs in medicine, engineering, management, pharmacy, and allied health sciences through 20+ constituent institutions.'
  },
  {
    id: '40',
    name: 'MIT — Manipal Institute of Technology',
    category: 'education',
    rating: 4.6,
    reviewCount: 5678,
    address: 'MIT Campus Road, Manipal',
    area: 'Manipal',
    phone: '+91 82022 22090',
    tags: ['Engineering', 'B.Tech', 'Research', 'Campus', 'Placement'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '5:00 PM',
    description: 'One of India\'s premier engineering institutions, consistently ranked in top 10 by NIRF. Excellent research facilities, global collaborations, and strong industry placement record.'
  },
  {
    id: '41',
    name: 'Udupi Central School (CBSE)',
    category: 'education',
    rating: 4.5,
    reviewCount: 178,
    address: 'Ajjarakadu, Udupi',
    area: 'Ajjarakadu',
    phone: '+91 82022 27700',
    tags: ['CBSE', 'K-12', 'English Medium', 'Sports', 'Labs'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '4:00 PM',
    description: 'CBSE-affiliated English medium school from Kindergarten to Class 12. Excellent academic record, modern science labs, sports facilities, and dedicated faculty.'
  },
  {
    id: '42',
    name: 'Poornaprajna College',
    category: 'education',
    rating: 4.3,
    reviewCount: 234,
    address: 'Udupi — Manipal Highway, Near Bus Stand',
    area: 'City Center',
    phone: '+91 82022 21330',
    tags: ['Degree College', 'Arts', 'Science', 'Commerce', 'PUC'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=400&q=80',
    openTime: '8:30 AM',
    closeTime: '4:30 PM',
    description: 'Premier college in Udupi offering PU and degree programs in Arts, Science and Commerce. Known for excellent teaching faculty, cultural activities, and consistent board exam results.'
  },

  // ─── SHOPPING ─────────────────────────────────────────────────
  {
    id: '43',
    name: 'City Centre Mall Udupi',
    category: 'shopping',
    rating: 4.0,
    reviewCount: 3456,
    address: 'Maruthi Veethika, Near Mosque Road, Udupi',
    area: 'City Center',
    phone: '+91 82022 29980',
    tags: ['Mall', 'Lifestyle', 'Food Court', 'Cinema', '225 Shops'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '9:30 PM',
    description: 'Udupi\'s largest shopping mall with 225 shops, a gaming zone, food court with 16 outlets, and terrace garden. Located 100m from the City Bus Stand. Branded stores, restaurants, and entertainment all under one roof.'
  },
  {
    id: '44',
    name: 'Canara Mall — Udupi',
    category: 'shopping',
    rating: 3.8,
    reviewCount: 1234,
    address: 'Eshwar Nagar, Near Manipal Highway',
    area: 'Kinnimulki',
    phone: '+91 82022 22100',
    tags: ['Mall', 'Clothing', 'Electronics', 'Food', 'Retail'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1567958451986-2de427a4a0be?w=400&q=80',
    openTime: '10:30 AM',
    closeTime: '9:00 PM',
    description: 'Well-established mall in Udupi with a good mix of retail stores, clothing brands, electronics, and eateries. Convenient parking and easy accessibility.'
  },
  {
    id: '45',
    name: 'Mookambika Silks & Textiles',
    category: 'shopping',
    rating: 4.3,
    reviewCount: 567,
    address: 'Car Street, Near Krishna Temple',
    area: 'Car Street',
    phone: '+91 82022 24455',
    tags: ['Sarees', 'Silks', 'Traditional', 'Dress Materials', 'Wedding'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '8:00 PM',
    description: 'Renowned textile store with a wide collection of Kanjivaram, Mysore, and Mangalagiri sarees along with blouse materials, dress fabrics, and ready-made garments for all occasions.'
  },
  {
    id: '46',
    name: 'Pai Computers & Electronics',
    category: 'shopping',
    rating: 4.2,
    reviewCount: 445,
    address: 'KC Road, Udupi',
    area: 'KC Road',
    phone: '+91 82022 28900',
    tags: ['Laptops', 'Mobiles', 'CCTV', 'Printers', 'Repairs'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1491933382434-500287f9b54b?w=400&q=80',
    openTime: '9:30 AM',
    closeTime: '8:00 PM',
    description: 'Trusted electronics store in Udupi selling laptops, mobile phones, CCTV systems, printers, and accessories. Also offers computer and phone repair services.'
  },
  {
    id: '47',
    name: 'D-Mart — Udupi',
    category: 'shopping',
    rating: 4.4,
    reviewCount: 2891,
    address: 'NH 66, Puttur Road, Udupi',
    area: 'NH 66',
    phone: '+91 82022 30000',
    tags: ['Supermarket', 'Groceries', 'FMCG', 'Home Appliances', 'Low Prices'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '10:00 PM',
    description: 'D-Mart hypermarket offering groceries, staples, clothing, home appliances, personal care, and more at consistently low prices. Huge parking area and a favourite for bulk shopping.'
  },

  // ─── PLACES / TEMPLES ─────────────────────────────────────────
  {
    id: '48',
    name: 'Sri Krishna Matha — Udupi',
    category: 'temples',
    rating: 4.9,
    reviewCount: 45678,
    address: 'Car Street, Udupi — 576101',
    area: 'Car Street',
    phone: '+91 82022 20761',
    tags: ['Temple', 'Famous', 'Pilgrim', 'Vegetarian Prasad', 'Paryaya'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=400&q=80',
    openTime: '5:00 AM',
    closeTime: '9:00 PM',
    description: 'Spiritual heart of Udupi, founded in 13th century by Madhvacharya. The deity is viewed through the unique Navagraha Kitiki (nine-hole window). The Paryaya festival every 2 years draws millions. Free prasad meals served daily in the community kitchen.'
  },
  {
    id: '49',
    name: 'Anantheshwara Temple, Udupi',
    category: 'temples',
    rating: 4.7,
    reviewCount: 5678,
    address: 'Court Road, Near Car Street',
    area: 'Car Street',
    phone: '',
    tags: ['Ancient Temple', 'Shiva Temple', 'Heritage', 'Udupi'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=400&q=80',
    openTime: '6:00 AM',
    closeTime: '8:30 PM',
    description: 'One of the oldest Shiva temples in Udupi, closely associated with the Krishna Matha. Located on the temple street in the historic car street area with beautiful Dravidian architecture.'
  },
  {
    id: '50',
    name: 'Kapu Beach & Lighthouse',
    category: 'travel',
    rating: 4.5,
    reviewCount: 8923,
    address: 'Kapu Village, 12 km from Udupi',
    area: 'Kapu',
    phone: '',
    tags: ['Beach', 'Lighthouse', 'Sunset', 'Photography', 'Tourism'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '6:00 PM',
    description: 'Serene coastal beach with a historic 19th-century lighthouse. Climb to the top for panoramic Arabian Sea views. Especially beautiful at sunset. 12 km from Udupi city, easily accessible by auto or cab.'
  },
  {
    id: '51',
    name: 'St. Mary\'s Islands — Boat Excursion',
    category: 'travel',
    rating: 4.8,
    reviewCount: 12456,
    address: 'Malpe Harbour (Boat Departure Point), Malpe',
    area: 'Malpe',
    phone: '+91 94480 78800',
    tags: ['Island', 'Basalt Rocks', 'Beach', 'UNESCO', 'Boating'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '4:30 PM',
    description: 'A group of uninhabited islands famous for striking hexagonal basalt rock formations dating back 88 million years. Accessible only by boat from Malpe (15 min ride). Clear waters and pristine beaches. One of Karnataka\'s most unique natural wonders.'
  },

  // ─── REAL ESTATE ──────────────────────────────────────────────
  {
    id: '52',
    name: 'Coastal Properties — Udupi',
    category: 'realestate',
    rating: 4.1,
    reviewCount: 78,
    address: 'Ajjarakadu Main Road, Udupi',
    area: 'Ajjarakadu',
    phone: '+91 82022 37400',
    tags: ['Residential', 'Commercial', 'Plots', 'Apartments', 'Villas'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&q=80',
    openTime: '9:30 AM',
    closeTime: '6:30 PM',
    description: 'Trusted real estate agent in Udupi with 15+ years experience. Specialises in residential apartments, commercial properties, land and plot sales, and rentals across Udupi and Manipal.'
  },
  {
    id: '53',
    name: 'Manipal Realty & Developers',
    category: 'realestate',
    rating: 4.0,
    reviewCount: 56,
    address: 'Tiger Circle, Manipal',
    area: 'Manipal',
    phone: '+91 82025 44555',
    tags: ['Apartments', 'Duplex', 'PG Rooms', 'Student Housing', 'Manipal'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=400&q=80',
    openTime: '9:00 AM',
    closeTime: '6:00 PM',
    description: 'Property agency specialising in Manipal area — student apartments, family flats, and commercial spaces near Manipal University. PG room listings and long-term rental assistance.'
  },

  // ─── PACKERS & MOVERS ─────────────────────────────────────────
  {
    id: '54',
    name: 'Coastal Packers & Movers',
    category: 'packers',
    rating: 4.0,
    reviewCount: 67,
    address: 'Industrial Area, Udupi',
    area: 'Industrial Area',
    phone: '+91 82020 01234',
    tags: ['Local Moving', 'Intercity', 'Storage', 'Car Transport'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '9:00 PM',
    description: 'Reliable packers and movers serving Udupi and coastal Karnataka. Safe household shifting, vehicle transport, warehousing, and office relocation with insurance coverage.'
  },
  {
    id: '55',
    name: 'Sri Krishna Packers',
    category: 'packers',
    rating: 4.1,
    reviewCount: 89,
    address: 'Kinnimulki, Udupi',
    area: 'Kinnimulki',
    phone: '+91 94480 56789',
    tags: ['House Shifting', 'Intercity', 'Bangalore', 'Goa', 'Fragile'],
    isVerified: false,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&q=80',
    openTime: '7:00 AM',
    closeTime: '8:00 PM',
    description: 'Budget-friendly packers and movers with routes to Bangalore, Mangalore, Goa, and Mumbai. Experienced in fragile goods, electronics packing, and door-to-door delivery.'
  },

  // ─── PG / HOSTEL ──────────────────────────────────────────────
  {
    id: '56',
    name: 'Manipal Student PG — Green Leaf',
    category: 'pghostel',
    rating: 4.2,
    reviewCount: 145,
    address: 'Vidyaratna Nagar, Manipal',
    area: 'Manipal',
    phone: '+91 96117 44400',
    tags: ['Furnished', 'Meals Included', 'Wi-Fi', 'AC', 'Laundry'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Well-maintained PG accommodation for students near MAHE campus. Fully furnished rooms, South Indian vegetarian meals included, 24-hour security, Wi-Fi, and laundry services.'
  },
  {
    id: '57',
    name: 'Cosmos Hostel — Manipal',
    category: 'pghostel',
    rating: 4.0,
    reviewCount: 234,
    address: 'MIT Road, Manipal',
    area: 'Manipal',
    phone: '+91 82025 88900',
    tags: ['Co-working', 'Dormitory', 'Single Rooms', 'International Students'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=400&q=80',
    openTime: '24 Hours',
    closeTime: '24 Hours',
    description: 'Modern hostel catering to international students in Manipal. Dormitory and private room options with co-working spaces, common lounge, and regular community events. Multi-cuisine meals available.'
  },

  // ─── LOANS / BANKING ──────────────────────────────────────────
  {
    id: '58',
    name: 'Corporation Bank — Udupi Main Branch',
    category: 'loans',
    rating: 3.9,
    reviewCount: 456,
    address: 'KM Marg, Corporation Bank Road, Udupi',
    area: 'City Center',
    phone: '+91 82022 25200',
    tags: ['Home Loan', 'Personal Loan', 'Education Loan', 'Business Loan'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '4:00 PM',
    description: 'Headquarters of the historic Corporation Bank (now Union Bank of India) — founded in Udupi. Comprehensive banking and loan services including home loans, MSME loans, and education financing.'
  },
  {
    id: '59',
    name: 'Canara Bank — Udupi Main',
    category: 'loans',
    rating: 3.8,
    reviewCount: 345,
    address: 'Ajjarakadu Road, Udupi',
    area: 'Ajjarakadu',
    phone: '+91 82022 23300',
    tags: ['Bank', 'Home Loan', 'Gold Loan', 'Fixed Deposits', 'NRI'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&q=80',
    openTime: '10:00 AM',
    closeTime: '4:00 PM',
    description: 'Major Canara Bank branch in Udupi offering full range of banking and financial services. Special schemes for NRIs, senior citizens, and Udupi\'s thriving business community.'
  },

  // ─── CATERERS / EVENTS ────────────────────────────────────────
  {
    id: 'ct1',
    name: 'Shubhamangala Catering Services',
    category: 'caterers',
    rating: 4.5,
    reviewCount: 312,
    address: 'Bannanje, Udupi',
    area: 'Bannanje',
    phone: '+91 94480 12345',
    tags: ['Weddings', 'Udupi Cuisine', 'South Indian', 'Vegetarian', 'Puja'],
    isVerified: true,
    isClosed: false,
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=400&q=80',
    openTime: '8:00 AM',
    closeTime: '9:00 PM',
    description: 'Expert catering for weddings, corporate events, pujas, and temple functions. Specialises in authentic Udupi-style banana leaf meals. Capacity for 50 to 5000+ guests with complete setup services.'
  },
];

export const MOCK_BUSINESSES: Business[] = [
  ...BASE_BUSINESSES,
  ...EXTRA_BUSINESSES_1,
  ...EXTRA_BUSINESSES_2,
  ...EXTRA_BUSINESSES_3,
  ...EXTRA_BUSINESSES_4,
  ...EXTRA_BUSINESSES_5,
];

export const BANNERS = [
  {
    id: '1',
    title: 'List your Business FREE',
    subtitle: 'Reach 50,000+ customers in Udupi District',
    ctaText: 'Get More Leads',
    bgColor: 'from-[#1a9e94] to-[#0d7a72]',
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=300&q=80',
    path: '/list-business',
  },
  {
    id: '2',
    title: 'Udupi Special Offers',
    subtitle: 'Exclusive deals from local businesses',
    ctaText: 'Explore Offers',
    bgColor: 'from-[#f05a28] to-[#c0410f]',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=300&q=80',
    path: '/offers',
  },
  {
    id: '3',
    title: 'B2B Marketplace — 500+ Suppliers',
    subtitle: 'Connect with verified Udupi businesses',
    ctaText: 'View Suppliers',
    bgColor: 'from-[#3b82f6] to-[#1d4ed8]',
    image: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=300&q=80',
    path: '/b2b',
  },
  {
    id: '4',
    title: 'Book Malpe Boat Tour',
    subtitle: "Visit St. Mary's Islands — hexagonal basalt rocks",
    ctaText: 'Book Now',
    bgColor: 'from-[#0891b2] to-[#155e75]',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=300&q=80',
    path: '/search?category=travel',
  },
];

export const NEWS_ITEMS = [
  {
    id: '1',
    title: 'Krishna Mutt announces special Paryaya puja schedule for upcoming season',
    time: '2 hours ago',
    category: 'Temples',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=200&q=80',
  },
  {
    id: '2',
    title: 'Kasturba Hospital Manipal launches new cardiac care wing with latest equipment',
    time: '5 hours ago',
    category: 'Health',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=200&q=80',
  },
  {
    id: '3',
    title: 'Udupi beach cleanup drive a massive success with 500+ volunteers at Malpe',
    time: '1 day ago',
    category: 'Community',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=200&q=80',
  },
  {
    id: '4',
    title: 'MAHE Manipal ranked among top 5 private universities in India — NIRF 2026',
    time: '2 days ago',
    category: 'Education',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=200&q=80',
  },
  {
    id: '5',
    title: 'City Centre Mall Udupi opens 10 new stores ahead of Paryaya festival season',
    time: '3 days ago',
    category: 'Business',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=200&q=80',
  },
  {
    id: '6',
    title: 'St. Mary\'s Islands boat tour bookings hit record high this tourist season',
    time: '4 days ago',
    category: 'Tourism',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=200&q=80',
  },
  {
    id: '7',
    title: 'Udupi district achieves 100% digital payment adoption across major markets',
    time: '5 days ago',
    category: 'Technology',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&q=80',
  },
  {
    id: '8',
    title: 'New Udupi-Mangaluru expressway proposed — to cut travel time by 40 minutes',
    time: '1 week ago',
    category: 'Infrastructure',
    image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=200&q=80',
  },
];
