import { useState } from 'react';
import { Phone, MessageCircle, MapPin, Search, ShoppingCart, Star, CheckCircle, X, RefreshCw, ChevronDown, Instagram, Facebook, Clock, Megaphone } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery, useMutation } from '@tanstack/react-query';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';

interface UserWebsite { id:string; slug:string; business_name:string; tagline?:string; category:string; about?:string; phone?:string; email?:string; address?:string; logo_url?:string; banner_url?:string; theme_color:string; template:string; whatsapp_number?:string; instagram_url?:string; facebook_url?:string; is_published:boolean; total_views:number; }
interface WebsiteProduct { id:string; name:string; description?:string; price:number; original_price?:number; category:string; images?:string[]; in_stock:boolean; is_featured:boolean; }

const ProductCard=({product,color,onOrder}:{product:WebsiteProduct;color:string;onOrder:(p:WebsiteProduct)=>void})=><div className="bg-white rounded-2xl overflow-hidden shadow-sm border border-gray-100"><div className="aspect-square bg-gray-100 relative">{product.images?.[0]?<img src={product.images[0]} alt={product.name} className="w-full h-full object-cover"/>:<div className="w-full h-full flex items-center justify-center text-5xl">🛍️</div>}{product.is_featured&&<span className="absolute top-2 right-2 bg-amber-400 text-white text-[10px] font-bold px-2 py-1 rounded-lg"><Star size={9} fill="white" className="inline"/> Top Pick</span>}</div><div className="p-3"><p className="font-heading font-bold text-gray-900 text-sm line-clamp-2">{product.name}</p>{product.description&&<p className="text-[10px] text-gray-400 mt-1 line-clamp-2">{product.description}</p>}<p className="font-bold text-base mt-2" style={{color}}>₹{Number(product.price||0).toLocaleString('en-IN')}</p><button onClick={()=>product.in_stock&&onOrder(product)} disabled={!product.in_stock} className="mt-2.5 w-full text-white font-bold text-xs py-2.5 rounded-xl flex items-center justify-center gap-1.5 disabled:opacity-50" style={{backgroundColor:product.in_stock?color:'#9ca3af'}}><ShoppingCart size={12}/>{product.in_stock?'Buy via WhatsApp':'Out of Stock'}</button></div></div>;

const OrderModal=({product,website,onClose}:{product:WebsiteProduct;website:UserWebsite;onClose:()=>void})=>{const [name,setName]=useState('');const [phone,setPhone]=useState('');const [qty,setQty]=useState(1);const [sent,setSent]=useState(false);const mutation=useMutation({mutationFn:async()=>{const {error}=await supabase.from('website_orders').insert({website_id:website.id,product_id:product.id,product_name:product.name,customer_name:name,customer_phone:phone,quantity:qty,total_amount:Number(product.price)*qty,status:'pending'});if(error)throw error;},onSuccess:()=>setSent(true),onError:(e:Error)=>toast.error(e.message)});const order=()=>{if(!name||!phone){toast.error('Please enter your name and phone');return;}const n=(website.whatsapp_number||website.phone||'').replace(/[\s+\-()]/g,'');const text=encodeURIComponent(`Hi! I want to order ${product.name}. Quantity: ${qty}. Total: ₹${(Number(product.price)*qty).toLocaleString('en-IN')}. Name: ${name}. Phone: ${phone}`);window.open(`https://wa.me/${n}?text=${text}`,'_blank');mutation.mutate();};return <div className="fixed inset-0 z-50 bg-black/60 flex items-end" onClick={onClose}><div className="w-full bg-white rounded-t-3xl p-5" onClick={e=>e.stopPropagation()}>{sent?<div className="text-center py-8"><CheckCircle size={48} className="text-green-500 mx-auto mb-3"/><h3 className="font-bold text-xl">Order Sent!</h3><button onClick={onClose} className="mt-5 px-6 py-2.5 rounded-xl text-white font-bold" style={{backgroundColor:website.theme_color}}>Done</button></div>:<><div className="flex justify-between items-center mb-4"><h3 className="font-bold text-lg">Order via WhatsApp</h3><button onClick={onClose}><X/></button></div><div className="bg-gray-50 rounded-xl p-3 mb-4"><b>{product.name}</b><p className="font-bold" style={{color:website.theme_color}}>₹{Number(product.price).toLocaleString('en-IN')}</p></div><label className="text-xs font-bold">Your Name *</label><input value={name} onChange={e=>setName(e.target.value)} className="w-full p-3 bg-gray-50 rounded-xl mb-3 mt-1" placeholder="Full name"/><label className="text-xs font-bold">Phone Number *</label><input value={phone} onChange={e=>setPhone(e.target.value)} className="w-full p-3 bg-gray-50 rounded-xl mb-3 mt-1" placeholder="+91 XXXXX XXXXX" type="tel"/><label className="text-xs font-bold">Quantity</label><div className="flex items-center gap-4 my-2"><button onClick={()=>setQty(Math.max(1,qty-1))} className="w-10 h-10 bg-gray-100 rounded-xl font-bold">−</button><b>{qty}</b><button onClick={()=>setQty(qty+1)} className="w-10 h-10 rounded-xl text-white font-bold" style={{backgroundColor:website.theme_color}}>+</button></div><button onClick={order} disabled={mutation.isPending} className="w-full bg-green-500 text-white font-bold py-3.5 rounded-xl flex items-center justify-center gap-2 disabled:opacity-60"><MessageCircle size={17}/>{mutation.isPending?'Sending...':'Order via WhatsApp'}</button></>}</div></div>};

const PublicStore=()=>{const {slug}=useParams<{slug:string}>();const navigate=useNavigate();const [search,setSearch]=useState('');const [category,setCategory]=useState('All');const [orderProduct,setOrderProduct]=useState<WebsiteProduct|null>(null);const [about,setAbout]=useState(false);
const {data:website,isLoading,error}=useQuery({queryKey:['public_store',slug],enabled:Boolean(slug),queryFn:async()=>{const {data,error}=await supabase.from('user_websites').select('*').eq('slug',slug!).eq('is_published',true).maybeSingle();if(error)throw error;if(data)supabase.from('user_websites').update({total_views:(data.total_views||0)+1}).eq('id',data.id);return data as UserWebsite|null;}});
const {data:products=[]}=useQuery({queryKey:['public_products',website?.id],enabled:Boolean(website?.id),queryFn:async()=>{const {data,error}=await supabase.from('website_products').select('*').eq('website_id',website!.id).eq('in_stock',true).order('is_featured',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return (data||[]) as WebsiteProduct[];}});
const {data:pages=[]}=useQuery({queryKey:['public_pages',website?.id],enabled:Boolean(website?.id),queryFn:async()=>{const {data,error}=await supabase.from('website_pages').select('*').eq('website_id',website!.id).eq('is_published',true).order('sort_order',{ascending:true});if(error)throw error;return data||[];}});
const {data:widgets=[]}=useQuery({queryKey:['public_widgets',website?.id],enabled:Boolean(website?.id),queryFn:async()=>{const {data,error}=await supabase.from('website_widgets').select('*').eq('website_id',website!.id).eq('is_active',true).order('sort_order',{ascending:true});if(error)throw error;return data||[];}});
if(isLoading)return <div className="min-h-screen flex items-center justify-center bg-gray-50"><div className="text-center"><RefreshCw className="animate-spin mx-auto text-gray-400"/><p className="text-gray-400 mt-3 text-sm">Loading store...</p></div></div>;
if(error||!website)return <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4"><div className="text-center"><div className="text-5xl mb-4">🏪</div><h2 className="font-bold text-xl">Store Not Found</h2><p className="text-gray-500 text-sm mt-2">This website may be unpublished or the link is invalid.</p><button onClick={()=>navigate('/')} className="mt-5 px-5 py-2.5 rounded-xl text-white font-bold" style={{backgroundColor:'#0d9488'}}>Go to UdupiGo</button></div></div>;
const color=website.theme_color||'#0d9488';const cats=['All',...Array.from(new Set(products.map(p=>p.category).filter(Boolean)))];const filtered=products.filter(p=>(category==='All'||p.category===category)&&(!search||p.name.toLowerCase().includes(search.toLowerCase())||(p.description||'').toLowerCase().includes(search.toLowerCase())));const announcement=widgets.find((w:any)=>w.widget_type==='announcement');const hours=widgets.find((w:any)=>w.widget_type==='hours');const testimonials=widgets.find((w:any)=>w.widget_type==='testimonials');
return <div className="min-h-screen bg-gray-50"><header className="sticky top-0 z-40 shadow-sm" style={{backgroundColor:color}}><div className="flex items-center gap-3 px-4 py-3"><div className="w-10 h-10 rounded-xl bg-white/20 overflow-hidden flex items-center justify-center">{website.logo_url?<img src={website.logo_url} className="w-full h-full object-cover" alt="Logo"/>:<span className="text-white font-bold text-lg">{website.business_name[0]}</span>}</div><div className="flex-1 min-w-0"><h1 className="font-bold text-white truncate">{website.business_name}</h1>{website.tagline&&<p className="text-white/70 text-[10px] truncate">{website.tagline}</p>}</div>{website.phone&&<a href={`tel:${website.phone}`} className="w-9 h-9 rounded-xl bg-white/20 flex items-center justify-center"><Phone size={16} className="text-white"/></a>}{website.whatsapp_number&&<a href={`https://wa.me/${website.whatsapp_number.replace(/[\s+\-()]/g,'')}`} target="_blank" rel="noopener noreferrer" className="w-9 h-9 rounded-xl bg-green-500 flex items-center justify-center"><MessageCircle size={16} className="text-white"/></a>}</div></header>{announcement&&<div className="px-4 py-2.5 text-white text-xs font-bold text-center" style={{backgroundColor:(announcement as any).config?.color||color}}><Megaphone size={12} className="inline mr-2"/>{(announcement as any).config?.message}</div>}{website.banner_url?<div className="h-48 overflow-hidden relative"><img src={website.banner_url} className="w-full h-full object-cover" alt={website.business_name}/><div className="absolute inset-0 bg-black/30"/></div>:<div className="h-36 flex items-center justify-center text-center text-white" style={{background:`linear-gradient(135deg,${color},${color}99)`}}><div><p className="font-bold text-2xl">{website.business_name}</p>{website.tagline&&<p className="text-sm text-white/80">{website.tagline}</p>}</div></div>}
{pages.length>0&&<div className="flex gap-2 px-4 pt-3 overflow-x-auto">{pages.map((p:any)=><button key={p.id} onClick={()=>document.getElementById(`page-${p.id}`)?.scrollIntoView({behavior:'smooth'})} className="flex-shrink-0 px-3 py-1.5 bg-white rounded-xl text-xs font-bold border border-gray-200">{p.title}</button>)}</div>}
<div className="px-4 py-3"><div className="bg-white rounded-2xl px-4 py-3 shadow-sm border border-gray-100 flex"><div className="flex-1 text-center border-r"><b className="text-lg">{products.length}</b><p className="text-[10px] text-gray-400">Products</p></div><div className="flex-1 text-center border-r"><b className="text-lg">{website.total_views||0}</b><p className="text-[10px] text-gray-400">Views</p></div><div className="flex-1 text-center"><b className="text-sm text-green-600">● Open</b><p className="text-[10px] text-gray-400">{website.category}</p></div></div></div>
<div className="px-4 mb-3"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${website.business_name} products...`} className="w-full pl-9 pr-4 py-2.5 bg-white border border-gray-200 rounded-xl text-sm outline-none"/></div></div><div className="flex gap-2 px-4 mb-4 overflow-x-auto">{cats.map(c=><button key={c} onClick={()=>setCategory(c)} className={`flex-shrink-0 px-4 py-2 rounded-xl text-xs font-bold ${category===c?'text-white':'bg-white text-gray-600 border border-gray-200'}`} style={category===c?{backgroundColor:color}:undefined}>{c}</button>)}</div>
<div className="px-4 pb-6">{filtered.length?<div className="grid grid-cols-2 gap-3">{filtered.map(p=><ProductCard key={p.id} product={p} color={color} onOrder={setOrderProduct}/>)}</div>:<div className="bg-white rounded-2xl p-12 text-center"><div className="text-4xl">📦</div><p className="font-bold text-gray-700 mt-2">{products.length?'No products found':'No products yet'}</p></div>}</div>
{(website.about||website.address)&&<div className="mx-4 mb-4 bg-white rounded-2xl border shadow-sm"><button onClick={()=>setAbout(!about)} className="w-full flex justify-between p-4 font-bold text-sm">About {website.business_name}<ChevronDown size={16} className={about?'rotate-180':''}/></button>{about&&<div className="px-4 pb-4 text-xs text-gray-500 space-y-3">{website.about&&<p>{website.about}</p>}{website.address&&<p><MapPin size={13} className="inline mr-1"/>{website.address}</p>}</div>}</div>}
{hours&&(hours as any).config&&<div className="mx-4 mb-4 bg-white rounded-2xl p-4 border"><div className="font-bold text-xs mb-3"><Clock size={14} className="inline mr-1" style={{color}}/>Business Hours</div>{['hours_mon','hours_sat','hours_sun'].map(k=>(hours as any).config[k]&&<p key={k} className="text-xs text-gray-500 mb-1">{k.replace('hours_','')}: {(hours as any).config[k]}</p>)}</div>}
{testimonials&&(testimonials as any).config&&(testimonials as any).config.review1&&<div className="mx-4 mb-4 bg-white rounded-2xl p-4 border"><p className="font-bold text-xs mb-3"><Star size={13} className="inline mr-1" style={{color}}/>Customer Reviews</p><p className="text-xs text-gray-600 italic">"{(testimonials as any).config.review1}"</p></div>}
{pages.map((p:any)=><div id={`page-${p.id}`} key={`content-${p.id}`} className="mx-4 mb-4 bg-white rounded-2xl p-4 border"><h2 className="font-bold text-lg" style={{color}}>{p.title}</h2><p className="text-sm text-gray-600 whitespace-pre-wrap mt-2">{p.content||'Coming soon...'}</p></div>)}
<div className="mx-4 mb-6 bg-white rounded-2xl border p-4 text-center"><p className="text-[10px] text-gray-400">Powered by</p><p className="font-bold"><span className="text-brand-teal">Udupi</span><span className="text-brand-coral">Go</span></p><button onClick={()=>navigate('/website-builder')} className="mt-3 px-4 py-2 rounded-xl text-white text-xs font-bold" style={{backgroundColor:color}}>Create Your Own Store →</button></div>{orderProduct&&<OrderModal product={orderProduct} website={website} onClose={()=>setOrderProduct(null)}/>}</div>};
export default PublicStore;
